//! The wire format exists twice — `sync.rs` and the window's `protocol.ts` —
//! and the two must agree byte for byte.
//!
//! M2.2 built a CI gate for exactly this risk on the schema and left the wire
//! format ungated. This is that gate: Rust writes the fixture, TypeScript
//! asserts against it, and CI fails if the committed file is stale.

use std::path::PathBuf;
use thought_mcp::lineage::ProseMirrorRangeHint;
use thoughtd::sync::{AnchoredMutation, Frame, LocalInputSource};

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/frames.json")
}

/// Frames chosen to cover what actually varies: every tag, an empty body, a
/// multi-byte document id, and a body containing the length prefix's own bytes.
fn cases() -> Vec<(&'static str, Frame)> {
    vec![
        (
            "subscribe-empty-vector",
            Frame::Subscribe {
                doc_id: "doc-1".into(),
                state_vector: vec![],
            },
        ),
        (
            "subscribe-with-vector",
            Frame::Subscribe {
                doc_id: "doc-1".into(),
                state_vector: vec![0, 1, 2, 255],
            },
        ),
        (
            "sync",
            Frame::Sync {
                doc_id: "doc-1".into(),
                update: vec![1, 0, 0, 0, 5],
            },
        ),
        (
            "update",
            Frame::Update {
                doc_id: "01a02d26-ac02-7072".into(),
                update: vec![42; 8],
            },
        ),
        (
            "sourced-update-paste",
            Frame::SourcedUpdate {
                doc_id: "doc-source".into(),
                source: LocalInputSource::Paste,
                update: vec![42, 0, 255],
            },
        ),
        (
            "anchored-batch",
            Frame::AnchoredBatch {
                doc_id: "doc-anchor".into(),
                mutations: vec![
                    AnchoredMutation {
                        source: LocalInputSource::Written,
                        client_event_id: "keyboard-🌿".into(),
                        hints: vec![
                            ProseMirrorRangeHint {
                                before_from: 1,
                                before_to: 4,
                                after_from: 1,
                                after_to: 7,
                            },
                            ProseMirrorRangeHint {
                                before_from: 20,
                                before_to: 20,
                                after_from: 23,
                                after_to: 25,
                            },
                        ],
                        update: vec![9, 8, 7],
                    },
                    AnchoredMutation {
                        source: LocalInputSource::Paste,
                        client_event_id: "paste-2".into(),
                        hints: vec![],
                        update: vec![0, 255, 1, 2],
                    },
                ],
            },
        ),
        (
            "broadcast",
            Frame::Broadcast {
                doc_id: "doc-2".into(),
                update: vec![7, 7, 7],
            },
        ),
        (
            "awareness",
            Frame::Awareness {
                doc_id: "doc-2".into(),
                payload: b"cursor".to_vec(),
            },
        ),
        (
            "error",
            Frame::Error {
                doc_id: "doc-3".into(),
                message: "no such document".into(),
            },
        ),
        (
            "presence",
            Frame::Presence {
                doc_id: "doc-2".into(),
                actor: r#"{"actor_id":"agent:opus","name":"opus"}"#.into(),
            },
        ),
        (
            "ack",
            Frame::Ack {
                doc_id: "doc-2".into(),
            },
        ),
        (
            // A non-ASCII id: the length prefix counts bytes, not characters,
            // and a decoder that slices by character position breaks here.
            "unicode-doc-id",
            Frame::Sync {
                doc_id: "документ".into(),
                update: vec![9],
            },
        ),
    ]
}

fn generate() -> String {
    let entries: Vec<serde_json::Value> = cases()
        .into_iter()
        .map(|(name, frame)| {
            serde_json::json!({
                "name": name,
                "frame": describe(&frame),
                "encoded": frame.encode(),
            })
        })
        .collect();
    serde_json::to_string_pretty(&serde_json::json!({
        "_comment": "Generated by `cargo test -p thoughtd --test wire_fixture`. \
                     The window's protocol.ts asserts against this.",
        "frames": entries,
    }))
    .unwrap()
        + "\n"
}

fn describe(frame: &Frame) -> serde_json::Value {
    let (kind, doc_id, body) = match frame {
        Frame::Subscribe {
            doc_id,
            state_vector,
        } => ("subscribe", doc_id, state_vector.clone()),
        Frame::Sync { doc_id, update } => ("sync", doc_id, update.clone()),
        Frame::Update { doc_id, update } => ("update", doc_id, update.clone()),
        Frame::SourcedUpdate {
            doc_id,
            source,
            update,
        } => {
            let source = match source {
                LocalInputSource::Unknown => 0,
                LocalInputSource::Written => 1,
                LocalInputSource::Paste => 2,
                LocalInputSource::Import => 3,
                LocalInputSource::Command => 4,
            };
            let mut body = vec![source];
            body.extend(update);
            ("sourced_update", doc_id, body)
        }
        Frame::AnchoredBatch { doc_id, mutations } => {
            let mut body = vec![1];
            body.extend_from_slice(&(mutations.len() as u16).to_be_bytes());
            for mutation in mutations {
                let source = match mutation.source {
                    LocalInputSource::Unknown => 0,
                    LocalInputSource::Written => 1,
                    LocalInputSource::Paste => 2,
                    LocalInputSource::Import => 3,
                    LocalInputSource::Command => 4,
                };
                body.push(source);
                body.push(mutation.client_event_id.len() as u8);
                body.extend_from_slice(mutation.client_event_id.as_bytes());
                body.extend_from_slice(&(mutation.hints.len() as u16).to_be_bytes());
                for hint in &mutation.hints {
                    body.extend_from_slice(&hint.before_from.to_be_bytes());
                    body.extend_from_slice(&hint.before_to.to_be_bytes());
                    body.extend_from_slice(&hint.after_from.to_be_bytes());
                    body.extend_from_slice(&hint.after_to.to_be_bytes());
                }
                body.extend_from_slice(&(mutation.update.len() as u32).to_be_bytes());
                body.extend_from_slice(&mutation.update);
            }
            ("anchored_batch", doc_id, body)
        }
        Frame::Broadcast { doc_id, update } => ("broadcast", doc_id, update.clone()),
        Frame::Awareness { doc_id, payload } => ("awareness", doc_id, payload.clone()),
        Frame::Error { doc_id, message } => ("error", doc_id, message.as_bytes().to_vec()),
        Frame::Presence { doc_id, actor } => ("presence", doc_id, actor.as_bytes().to_vec()),
        Frame::Ack { doc_id } => ("ack", doc_id, vec![]),
    };
    serde_json::json!({ "kind": kind, "doc_id": doc_id, "body": body })
}

#[test]
fn fixture_is_current() {
    let generated = generate();
    let path = fixture_path();

    if std::env::var("UPDATE_FIXTURES").is_ok() {
        std::fs::write(&path, &generated).expect("write fixture");
        return;
    }

    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    assert_eq!(
        committed, generated,
        "\nThe wire fixture is stale, so Rust and the window disagree about the \
         protocol.\nRegenerate: UPDATE_FIXTURES=1 cargo test -p thoughtd --test wire_fixture\n"
    );
}

/// Rust must also read back what it writes, or the fixture only proves the
/// encoder is self-consistent.
#[test]
fn every_fixture_frame_decodes_to_itself() {
    for (name, frame) in cases() {
        let decoded =
            Frame::decode(&frame.encode()).unwrap_or_else(|| panic!("`{name}` failed to decode"));
        assert_eq!(
            describe(&decoded),
            describe(&frame),
            "`{name}` changed in transit"
        );
    }
}

#[test]
fn every_local_input_source_round_trips() {
    for source in [
        LocalInputSource::Unknown,
        LocalInputSource::Written,
        LocalInputSource::Paste,
        LocalInputSource::Import,
        LocalInputSource::Command,
    ] {
        let frame = Frame::SourcedUpdate {
            doc_id: "doc-source".into(),
            source,
            update: vec![1, 2, 3],
        };
        let decoded = Frame::decode(&frame.encode()).expect("sourced frame decodes");
        match decoded {
            Frame::SourcedUpdate {
                source: decoded,
                update,
                ..
            } => {
                assert_eq!(decoded, source);
                assert_eq!(update, vec![1, 2, 3]);
            }
            other => panic!("expected sourced update, got {other:?}"),
        }
    }
}

#[test]
fn anchored_batch_round_trips_every_field_in_order() {
    let (_, frame) = cases()
        .into_iter()
        .find(|(name, _)| *name == "anchored-batch")
        .expect("anchored fixture case");
    let decoded = Frame::decode(&frame.encode()).expect("anchored batch decodes");
    match decoded {
        Frame::AnchoredBatch { doc_id, mutations } => {
            assert_eq!(doc_id, "doc-anchor");
            assert_eq!(mutations.len(), 2);
            assert_eq!(mutations[0].client_event_id, "keyboard-🌿");
            assert_eq!(mutations[0].hints.len(), 2);
            assert_eq!(mutations[0].hints[1].after_from, 23);
            assert_eq!(mutations[0].update, vec![9, 8, 7]);
            assert_eq!(mutations[1].source, LocalInputSource::Paste);
            assert!(mutations[1].hints.is_empty());
            assert_eq!(mutations[1].update, vec![0, 255, 1, 2]);
        }
        other => panic!("expected anchored batch, got {other:?}"),
    }
}

/// A truncated or hostile frame must return None, never panic — it arrives on
/// a connection task that would take the endpoint down with it.
#[test]
fn malformed_frames_are_refused_rather_than_panicking() {
    assert!(Frame::decode(&[]).is_none(), "empty");
    assert!(
        Frame::decode(&[0x02, 0, 0]).is_none(),
        "shorter than the header"
    );
    // A length prefix claiming more bytes than the frame contains.
    assert!(
        Frame::decode(&[0x02, 0xff, 0xff, 0xff, 0xff]).is_none(),
        "absurd length"
    );
    assert!(
        Frame::decode(&[0x02, 0, 0, 0, 9, b'a']).is_none(),
        "id longer than body"
    );
    // An unknown tag is not a frame we understand.
    assert!(Frame::decode(&[0x7f, 0, 0, 0, 0]).is_none(), "unknown tag");
    // A sourced update must carry one of the closed source bytes before Yjs.
    assert!(
        Frame::decode(&[0x09, 0, 0, 0, 0]).is_none(),
        "missing source"
    );
    assert!(
        Frame::decode(&[0x09, 0, 0, 0, 0, 0x7f]).is_none(),
        "unknown source"
    );
}

fn anchored_wire(body: &[u8]) -> Vec<u8> {
    let mut frame = vec![0x0a, 0, 0, 0, 0];
    frame.extend_from_slice(body);
    frame
}

#[test]
fn malformed_anchored_batches_are_refused_rather_than_panicking() {
    let valid = Frame::AnchoredBatch {
        doc_id: String::new(),
        mutations: vec![AnchoredMutation {
            source: LocalInputSource::Written,
            client_event_id: "x".into(),
            hints: vec![],
            update: vec![1],
        }],
    }
    .encode();
    let valid_body = &valid[5..];

    let cases = [
        vec![],
        vec![2, 0, 1],
        vec![1, 0, 0],
        vec![1, 0, 129],
        vec![1, 0, 1],
        vec![1, 0, 1, 0x7f, 1, b'x', 0, 0, 0, 0, 0, 1, 1],
        vec![1, 0, 1, 1, 0],
        vec![1, 0, 1, 1, 1, 0xff, 0, 0, 0, 0, 0, 1, 1],
        vec![1, 0, 1, 1, 1, b'x', 0, 65],
        vec![
            1, 0, 1, 1, 1, b'x', 0, 1, 0, 0, 0, 5, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        ],
        vec![1, 0, 1, 1, 1, b'x', 0, 0, 0, 0, 0, 0],
        vec![1, 0, 1, 1, 1, b'x', 0, 0, 0, 0, 0, 2, 1],
        vec![1, 0, 1, 1, 1, b'x', 0, 0, 0xff, 0xff, 0xff, 0xff],
        {
            let mut trailing = valid_body.to_vec();
            trailing.push(0);
            trailing
        },
    ];

    for (index, body) in cases.into_iter().enumerate() {
        assert!(
            Frame::decode(&anchored_wire(&body)).is_none(),
            "malformed anchored case {index} decoded"
        );
    }
}

#[test]
fn every_truncation_of_an_anchored_batch_is_refused() {
    let frame = Frame::AnchoredBatch {
        doc_id: String::new(),
        mutations: vec![AnchoredMutation {
            source: LocalInputSource::Command,
            client_event_id: "event-🌿".into(),
            hints: vec![ProseMirrorRangeHint {
                before_from: 1,
                before_to: 2,
                after_from: 3,
                after_to: 4,
            }],
            update: vec![1, 2, 3, 4],
        }],
    }
    .encode();

    for len in 0..frame.len() {
        assert!(
            Frame::decode(&frame[..len]).is_none(),
            "truncation at byte {len} decoded"
        );
    }
    assert!(Frame::decode(&frame).is_some());
}
